server:
  port: 9080

spring:
  application:
    name: view
  cloud:
    openfeign:
      client:
        config:

          auth:
            url: http://localhost:8765/api/auth
            connection-timeout: 5000
            read-timeout: 5000

          hero:
            url: http://localhost:8765/api/hero
            connection-timeout: 5000
            read-timeout: 5000

          event:
            url: http://localhost:8765/api/event
            connection-timeout: 5000
            read-timeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 75
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 5
        maxWaitDurationInHalfOpenState: 5s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordFailurePredicate: ru.service.view.config.ClientRecordFailurePredicate
    instances:
      defaultCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 10s
